### ISSUE TITLE
显示全部commit信息

### ISSUE THREAD

**Issue by RanchoCooper** [LittleKey/dotfiles#1]
昨晚发版发现`git hist`只输出了commit msg的标题信息，而没有内容信息。
下面的配置可以用蓝色显示内容信息

 `hist = log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cblue%b %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit`

**Comment by LittleKey** [comment]
好像只是加上了pr的title?

**Comment by RanchoCooper** [comment]
两个仓库现在没有fork关系，提不了pr.. 
就是gitconfig改了一点点格式化的东西

**Comment by LittleKey** [comment]
👌  感觉那个作用并不大呀, 先close了
